
import ProductCard from '@/app/components2/productcard/productcard';
import { getCategoryDetails } from '@/APIs/categories';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Category Details",
  description: "Generated by create next app",
};

export default async function CategoryDetails({params}:{params:{id:string}}) {

  const {id} =await params;

  
  const data = await getCategoryDetails(id);
    


  return (
    <div className="bg-white text-gray-900">
      <div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8">
      <Link href="/web/categories" className="flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-green-600 transition-colors mb-8">
            <ArrowLeft className="h-4 w-4" />
            Back to All Categories
          </Link>
        <nav className="text-xs font-bold uppercase tracking-widest text-gray-400">
            
          Home / Shop / <span className="text-gray-900">{data[0]?data[0].category.name:''}</span>
        </nav>
      </div>

      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="border-b border-gray-100 pb-6 pt-10">
            <h1 className="text-4xl font-extrabold tracking-tight text-gray-900">{data[0] ?data[0].category.name:''}</h1>
        </div>

        <section className="pb-24 pt-6">
          {data.length>0? 
          <div className="grid grid-cols-1 md:grid-cols-4 lg:grid-cols-5 gap-3">
                {data.map((product) => (
                        <ProductCard key={product._id} product={product}  />
                      ))
                    }
              </div>:
                        <div className="flex flex-col items-center justify-center py-20 text-center">
                      <p className="text-xl font-medium text-gray-400">No products found for this category yet.</p>
                    </div>}

        </section>
      </main>

    </div>
  );
}