import ProductCard from "@/app/components2/productcard/productcard";
import { getBrandDetails } from "@/APIs/brand";
import { Star, ArrowLeft, LayoutGrid } from "lucide-react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Brand Details",
  description: "Generated by create next app",
};

export default async function page({ params }: { params: { id: string } }) {
  const { id } = await params;
  const brand = await getBrandDetails(id);

  return (
    <div className="min-h-screen bg-white">
      <div className="bg-gray-50 border-b border-gray-100">
        <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
          <Link
            href={"/web/brands"}
            className="flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-green-600 transition-colors mb-8"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to All Brands
          </Link>

          <div className="flex flex-col md:flex-row items-center gap-8">
            <div className="relative h-40 w-40 flex-shrink-0 rounded-3xl bg-white p-6 shadow-xl shadow-gray-200/50 ring-1 ring-gray-100">
              <img
                src={brand[0] && brand[0].imageCover}
                alt={brand[0] && brand[0].title}
                className="h-full w-full object-contain"
              />
            </div>

            <div className="text-center md:text-left">
              <h1 className="text-4xl font-black tracking-tight text-gray-900 sm:text-5xl">
                {brand[0] && brand[0].title} Collection
              </h1>
              <div className="mt-4 flex flex-wrap justify-center md:justify-start gap-6">
                <div className="flex items-center gap-2">
                  <span className="text-2xl font-bold text-gray-900">
                    {brand.length}
                  </span>
                  <span className="text-sm font-medium text-gray-500">
                    Products
                  </span>
                </div>
                <div className="h-8 w-px bg-gray-200 hidden sm:block" />
                <div className="flex items-center gap-2">
                  <Star className="h-5 w-5 fill-yellow-400 text-yellow-400" />
                  <span className="text-sm font-bold text-gray-900">
                    Top Rated Brand
                  </span>
                </div>
              </div>
              <p className="mt-4 max-w-xl text-gray-500 leading-relaxed">
                Discover the latest arrivals and most popular items from{" "}
                {brand[0] && brand[0].title}. Experience premium quality and
                official manufacturer warranty on every purchase.
              </p>
            </div>
          </div>
        </div>
      </div>

      <main className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="mb-10 flex items-center justify-between border-b border-gray-100 pb-6">
          <div className="flex items-center gap-2">
            <LayoutGrid className="h-5 w-5 text-green-600" />
            <h2 className="text-lg font-bold text-gray-900 tracking-tight">
              Available Items
            </h2>
          </div>
        </div>

        {brand.length > 0 ? (
          <div className="grid grid-cols-1 gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {brand.map((product) => (
              <ProductCard key={product._id} product={product} />
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <p className="text-xl font-medium text-gray-400">
              No products found for this brand yet.
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
