import CheckoutScreen from "./components/CheckoutScreen/CheckoutScreen";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <CheckoutScreen />
    </>
  );
}
