import ProductCard from "@/app/components2/productcard/productcard";
import { getAllProducts } from "@/APIs/products.api";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default async function Products() {
  const products = await getAllProducts();

  return (
    <div className="container mx-auto w-[95%] lg:w-[90%] my-10">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Products</h2>
        <div className="h-1 flex-grow mx-4 bg-gray-100 rounded-full hidden md:block"></div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 lg:grid-cols-5 gap-3">
        {products.map((product) => (
          <ProductCard product={product} key={product._id} />
        ))}
      </div>
    </div>
  );
}
