import CategoryCard from "@/app/components2/categorycard/categorycard";
import { getAllCategories } from "@/APIs/categories";
import { LayoutGrid, SlidersHorizontal } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by create next app",
};

export default async function categories() {
  const allCategories = await getAllCategories();

  return (
    <>
      <div className="min-h-screen bg-white">
        <div className="bg-gray-50 border-b border-gray-200">
          <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
            <nav className="flex mb-4 text-sm font-medium text-gray-500">
              <ol className="flex items-center space-x-2">
                <li>Home</li>
                <li>/</li>
                <li className="text-green-600 font-semibold">Shop All</li>
              </ol>
            </nav>
            <h1 className="text-4xl font-extrabold tracking-tight text-gray-900">
              New Arrivals
            </h1>
            <p className="mt-3 text-lg text-gray-500 max-w-2xl">
              Check out our latest drops. High-quality essentials designed for
              your modern lifestyle.
            </p>
          </div>
        </div>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="py-8">
            <main className="flex-1">
              <div className="mb-8 flex items-center justify-between border-b border-gray-100 pb-5">
                <button className="flex items-center gap-2 font-semibold text-gray-700 lg:hidden">
                  <SlidersHorizontal className="h-5 w-5" /> Filters
                </button>

                <div className="hidden lg:flex items-center gap-4 text-gray-400">
                  <LayoutGrid className="h-5 w-5 text-green-600 cursor-pointer" />
                  <span className="text-sm text-gray-500 ml-2">
                    Showing {allCategories.length} products
                  </span>
                </div>
              </div>
              <div className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 xl:grid-cols-3">
                {allCategories.map((category) => (
                  <CategoryCard key={category._id} category={category} />
                ))}
              </div>
            </main>
          </div>
        </div>
      </div>
    </>
  );
}
