import { getAllBrands } from "@/APIs/brand";
import { ArrowRight, Building2 } from "lucide-react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Brand",
  description: "Generated by create next app",
};

export default async function page() {
  const brands = await getAllBrands();
  return (
    <div className="min-h-screen bg-gray-50/50">
      <div className="bg-white border-b border-gray-200">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl">
            Our Brands
          </h1>
          <p className="mt-4 text-lg text-gray-500 max-w-2xl mx-auto">
            We partner with the world's most trusted brands to bring you the
            highest quality products.
          </p>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        {brands.length > 0 ? (
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
            {brands.map((brand) => (
              <Link
                key={brand._id}
                href={`/web/brandDetails/${brand._id}`}
                className="group relative flex flex-col items-center justify-center rounded-2xl border border-gray-200 bg-white p-6 transition-all duration-300 hover:border-green-500 hover:shadow-xl hover:shadow-green-50/50"
              >
                <div className="relative h-20 w-full mb-4 transition-transform duration-300 group-hover:scale-110">
                  <img
                    src={brand.image}
                    alt={brand.name}
                    className="h-full w-full object-contain filter grayscale group-hover:grayscale-0 transition-all"
                  />
                </div>
                <h3 className="text-sm font-bold text-gray-900 text-center">
                  {brand.name}
                </h3>
                <div className="mt-2 flex items-center gap-1 text-[10px] font-bold uppercase tracking-widest text-green-600 opacity-0 group-hover:opacity-100 transition-opacity">
                  View Store <ArrowRight className="h-3 w-3" />
                </div>
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-20">
            <Building2 className="mx-auto h-12 w-12 text-gray-300" />
            <h2 className="mt-4 text-xl font-semibold text-gray-900">
              No brands found
            </h2>
            <p className="text-gray-500">Try adjusting your search term.</p>
          </div>
        )}
      </div>
    </div>
  );
}
